name: KaMC_Utility_Plugin
main: top.DrakGod.KaMCUP.Main
version: 1.0.1
api-version: 1.20.6
description: 这是一个专门为KaMC打造的插件
authors: [Drakgod]
website: https://www.kamc.fun
depend: [Essentials]

commands:
  bank:
    description: 银行功能,可取可存
    usage: /bank <extract|save> [all|hand|money]
    aliases: [kabank]
    permission: kamcup.commands.bank
  car:
    description: 领取一个矿车,冷却10秒
    usage: /car
    aliases: []
    permission: kamcup.commands.car
  help:
    description: 查看KaMC实用插件帮助
    usage: /help <Page>
    aliases: [kahelp]
    permission: kamcup.commands.help
  kamcup:
    description: KaMC实用插件主指令
    usage: /kamcup <Commands>
    aliases: [kaup]
    permission: kamcup.commands.kamcup
  uuid:
    description: 获取一个玩家的uuid
    usage: /uuid <Player>
    aliases: []
    permission: kamcup.commands.uuid
  
permissions:
  kamcup.*:
    description: 授予对所有kamcup命令的访问权限
    default: op
    children:
      kamcup.admin: true
  kamcup.admin:
    description: 授予管理员权限
    default: false
    children:
      kamcup.commands.*: true
  kamcup.commands.*: 
    description: 授予执行命令权限
    default: false
    children:
      kamcup.commands.bank: true
      kamcup.commands.car: true
      kamcup.commands.help: true
      kamcup.commands.kamcup: true
      kamcup.commands.uuid: true
      kamcup.commands.kamcup.*: true
  kamcup.commands.bank:
    description: 授予执行/bank权限
    default: true
  kamcup.commands.car:
    description: 授予执行/car权限
    default: true
  kamcup.commands.help:
    description: 授予执行/help权限
    default: true
  kamcup.commands.kamcup:
    description: 授予执行/kamcup权限
    default: true
  kamcup.commands.uuid:
    description: 授予执行/uuid权限
    default: false
  kamcup.commands.kamcup.*:
    description: 授予执行/kamcup附属命令权限
    default: false
    children:
      kamcup.commands.kamcup.reload: true
      kamcup.commands.kamcup.version: true
  kamcup.commands.kamcup.reload:
    description: 授予执行/kamcup reload权限
    default: false
  kamcup.commands.kamcup.version:
    description: 授予执行/kamcup version权限
    default: false